notifications:
  email:
    - madhon@madhon.co.uk
language: csharp
solution: Ostrich.sln
install:
  - nuget restore Ostrich.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner -ExcludeVersion
script:
  - xbuild /p:Configuration=Release Ostrich.sln
  - mono ./testrunner/xunit.runners/tools/xunit.console.clr4.exe ./Ostrich.Tests/bin/Release/Ostrich.Tests.dll